version: '2'
services:
  frontend:
    build: frontend/
    ports:
     - "8080:8080"
  backend:
    build: backend/
    ports:
    - "8081:8081"
  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"
